In [1]:
import numpy as np

*NumPy provides efficient storage.
It also provides better ways of handling data for processing.
It is fast,easy to learn 
Numpy uses relatively less memory to store data*

In [ ]:
myarr = np.array([3,4,2,4,2,32])

In [10]:
a = (2,3,4,5,2) 
newarr = np.array(a)
print(newarr)

[2 3 4 5 2]


In [11]:
newarr.dtype

dtype('int32')

In [ ]:
myarr

In [ ]:
myarr.dtype

In [ ]:
myarr2 =np.array([[3,3,5,6,3,2]],np.int32)

In [ ]:
myarr2

In [ ]:
myarr2[0]

In [ ]:
#myarr2[2]

In [ ]:
myarr2[0][2]

In [ ]:
myarr.shape

In [ ]:
myarr2.shape

In [ ]:
myarr2[0,1]=12

In [ ]:
myarr2

## Array creation

In [12]:
listarray =np.array([[1,2,3],[5,8,6],[2,4,0]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [2, 4, 0]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
np.array({34,43,54})

array({34, 43, 54}, dtype=object)

In [20]:
np.array({"ewr","dkf","dkf"})

array({'dkf', 'ewr'}, dtype=object)

In [23]:
zeros =np.zeros((2,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
rng = np.arange(15)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace = np.linspace(1,7,12) 
#ek se 7 k beech 12 element chahiye

In [35]:
lspace

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [40]:
emp= np.empty((4,3))

In [41]:
emp

array([[1.        , 1.54545455, 2.09090909],
       [2.63636364, 3.18181818, 3.72727273],
       [4.27272727, 4.81818182, 5.36363636],
       [5.90909091, 6.45454545, 7.        ]])

In [42]:
emp_like =np.empty_like((lspace))

In [43]:
emp_like

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [44]:
iden = np.identity(7)

In [45]:
iden

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [46]:
arr = np.arange(99)

In [48]:
arr.reshape(3,33) #arr.dtype #arr.shape

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [51]:
arr.ravel() ##linerly alligned  having arr.shape -> (99,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# axis 0 is column and axis 1 is row

In [52]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [2, 4, 0]])

In [53]:
listarray.sum(axis=0)

array([ 8, 14,  9])

In [54]:
listarray.sum(axis=1)

array([ 6, 19,  6])

In [57]:
listarray.T

array([[1, 5, 2],
       [2, 8, 4],
       [3, 6, 0]])

In [58]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [2, 4, 0]])

In [61]:
listarray.flat

In [64]:
for item in listarray.flat:
    print(item)

1
2
3
5
8
6
2
4
0


In [67]:
listarray.ndim

2

In [68]:
listarray.size

9

In [69]:
listarray.nbytes

36

In [70]:
one =np.array([2,4,5,54,242])

In [72]:
one.argmax() # Gives max Index

4

In [73]:
one.argmin()

0

In [75]:
one.argsort() # indices to be sort

array([0, 1, 2, 3, 4], dtype=int64)

In [77]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [2, 4, 0]])

In [78]:
listarray.argmin()

8

In [79]:
listarray.argmax()

4

In [80]:
listarray.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [81]:
listarray.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [85]:
listarray

array([[1, 2, 3],
       [5, 8, 6],
       [2, 4, 0]])

In [86]:
listarray.argsort() # By default in row major or Axis =1

array([[0, 1, 2],
       [0, 2, 1],
       [2, 0, 1]], dtype=int64)

In [87]:
listarray.argsort(axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [2, 0, 1]], dtype=int64)

In [88]:
listarray.argsort(axis=0)

array([[0, 0, 2],
       [2, 2, 0],
       [1, 1, 1]], dtype=int64)

In [90]:
listarray.ravel()

array([1, 2, 3, 5, 8, 6, 2, 4, 0])

# Operations supported by NumPy Array

In [108]:
a1 =np.arange(3,9)

In [109]:
a1=a1.reshape(3,2)

In [103]:
a2=np.empty_like(a1)

In [110]:
a1

array([[3, 4],
       [5, 6],
       [7, 8]])

In [104]:
a2

array([[-1666532512,         587],
       [          0,           0],
       [     131074,     6357100]])

In [105]:
a2.dtype

dtype('int32')

In [106]:
a2.reshape(3,2)

array([[-1666532512,         587],
       [          0,           0],
       [     131074,     6357100]])

In [107]:
a1+a2

array([[-1666532509,         591],
       [          5,           6],
       [     131081,     6357108]])

In [111]:
a1*a2

array([[-704630240,       2348],
       [         0,          0],
       [    917518,   50856800]])

In [112]:
a1.sum()

33

In [113]:
a1.max()

8

In [114]:
a1

array([[3, 4],
       [5, 6],
       [7, 8]])

In [116]:
np.where(a1>3)

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 0, 1, 0, 1], dtype=int64))